export const Productos = [
    {
        id:1,
        nombre: "HATER BLANCO",
        descripcion: "REMERA OVERSIZE",
        precio: 2000,
        img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/994/528/products/img_38671-eb8474dec40d1b633916840227726018-640-0.webp",
    },
    {
        id:2,
        nombre: "HATER BLANCO",
        descripcion: "REMERA OVERSIZE",
        precio: 2000,
        img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/994/528/products/img_38671-eb8474dec40d1b633916840227726018-640-0.webp",
    },
    {
        id:3,
        nombre: "HATER BLANCO",
        descripcion: "REMERA OVERSIZE",
        precio: 2000,
        img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/994/528/products/img_38671-eb8474dec40d1b633916840227726018-640-0.webp",
    },
    {
        id:4,
        nombre: "HATER BLANCO",
        descripcion: "REMERA OVERSIZE",
        precio: 2000,
        img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/994/528/products/img_38671-eb8474dec40d1b633916840227726018-640-0.webp",
    },
    {
        id:5,
        nombre: "HATER BLANCO",
        descripcion: "REMERA OVERSIZE",
        precio: 2000,
        img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/994/528/products/img_38671-eb8474dec40d1b633916840227726018-640-0.webp",
    },
    {
        id:6,
        nombre: "HATER BLANCO",
        descripcion: "REMERA OVERSIZE",
        precio: 2000,
        img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/994/528/products/img_38671-eb8474dec40d1b633916840227726018-640-0.webp",
    },






]